"""bot-ea core package."""

from .codex_cli_engine import CodexCLIEngine
from .models import (
    AccountSnapshot,
    Bar,
    CapitalAllocation,
    CapitalAllocationMode,
    ExecutionGateResult,
    OperatingMode,
    PositionSizeRequest,
    PositionSizeResult,
    RiskPolicy,
    SymbolSnapshot,
    TradingStyle,
)
from .mt5_adapter import (
    AccountFingerprintSnapshot,
    LiveMT5Adapter,
    MockMT5Adapter,
    MT5Adapter,
    MutationAccountBinding,
    OrderSendResult,
    OrderValidationResult,
    PriceTickSnapshot,
    SymbolCapabilitySnapshot,
    TerminalStatusSnapshot,
)
from .mt5_execution_runtime import MT5ExecutionRuntime
from .mt5_snapshots import build_account_snapshot, build_symbol_snapshot
from .polling_runtime import (
    AIIntent,
    DecisionAction,
    MT5SnapshotProvider,
    PollingConfig,
    PollingCycleResult,
    PollingRuntime,
    RuntimeSnapshot,
)
from .risk_engine import RiskEngine
from .runtime_store import RuntimeStore
from .stop_policy import (
    SessionPerformance,
    StopDecision,
    StopPolicy,
    StopReason,
    evaluate_stop_policy,
)
from .validation import (
    ExecutionQualitySummary,
    OOSWindowResult,
    PromotionAuditRecord,
    PromotionCandidate,
    PromotionCheckResult,
    PromotionDecision,
    PromotionGateThresholds,
    RuntimeValidationReport,
    TradeRecord,
    ValidationSummary,
    build_promotion_audit_record,
    build_runtime_validation_report,
    build_trade_records_from_runtime,
    evaluate_cost_realism,
    evaluate_promotion_gate,
    export_promotion_audit_json,
    export_promotion_audit_markdown,
    export_summary_markdown,
    summarize_execution_quality,
    summarize_trades,
)

__all__ = [
    "AIIntent",
    "AccountFingerprintSnapshot",
    "AccountSnapshot",
    "Bar",
    "CapitalAllocation",
    "CapitalAllocationMode",
    "CodexCLIEngine",
    "DecisionAction",
    "ExecutionGateResult",
    "ExecutionQualitySummary",
    "LiveMT5Adapter",
    "MT5Adapter",
    "MT5ExecutionRuntime",
    "MT5SnapshotProvider",
    "MockMT5Adapter",
    "MutationAccountBinding",
    "OOSWindowResult",
    "OperatingMode",
    "OrderSendResult",
    "OrderValidationResult",
    "PollingConfig",
    "PollingCycleResult",
    "PollingRuntime",
    "PositionSizeRequest",
    "PositionSizeResult",
    "PriceTickSnapshot",
    "PromotionAuditRecord",
    "PromotionCandidate",
    "PromotionCheckResult",
    "PromotionDecision",
    "PromotionGateThresholds",
    "RiskEngine",
    "RiskPolicy",
    "RuntimeSnapshot",
    "RuntimeStore",
    "RuntimeValidationReport",
    "SessionPerformance",
    "StopDecision",
    "StopPolicy",
    "StopReason",
    "SymbolCapabilitySnapshot",
    "SymbolSnapshot",
    "TerminalStatusSnapshot",
    "TradeRecord",
    "TradingStyle",
    "ValidationSummary",
    "build_account_snapshot",
    "build_promotion_audit_record",
    "build_runtime_validation_report",
    "build_symbol_snapshot",
    "build_trade_records_from_runtime",
    "evaluate_cost_realism",
    "evaluate_promotion_gate",
    "evaluate_stop_policy",
    "export_promotion_audit_json",
    "export_promotion_audit_markdown",
    "export_summary_markdown",
    "summarize_execution_quality",
    "summarize_trades",
]
